### ISSUE TITLE
还活着哦？

### ISSUE THREAD

**Issue by ghost** [RootHarold/LycorisAD#1]
还活着哦？

**Comment by RootHarold** [comment]
Thank you very much for your support and attention. This project will be developed continuously and iteratively. And Happy New Year.

**Comment by bxzzy** [comment]
Long time no see. 送你个饿了吗会员账号哦，我在这边用不了。。。账号18795508953 正好你不用出去吃

**Comment by bxzzy** [comment]
欸，其实我挺想告诉他的，可是是他让我问问你的，他全都看到了，也没法在告诉了。当时，我们就商量好了，过了一段时间，看看你有没有变化。武汉这次是个机会，结果还是一样，我也没啥话好说的了。其实，你那些东西一点用都没有，最后我全都删了，我早就和我的advisor聊过了。他让我直接把你删了，我想了好久这次关系是真的完全结束了，但是我想和你做最后的告别，我这个github也不会在用了，我的那个手机号是国内临时的，本来想把我这边手机号告诉你的，其实大四一整年，我们三一块玩的还挺开心的。希望你能找到真正的朋友，永别了！
